local echo = demonnic.helpers.echo
local validOptions = table.keys(demonnic.config)
table.sort(validOptions)
local validOptionsString = table.concat(validOptions, ", ")
echo("Usage information for changing emco colors")
echo()
echo("emco color <option> <color>")
echo("Color can be anything you would use in CSS, such as 'rgb(128,128,128)', '#888888', or 'grey'")
echo("examples:")
echo("  * emco color activeBorder goldenrod")
echo("    * changes the border around the active tab to goldenrod")
echo("  * emco color activeColor #00ff00")
echo("    * changes the color of the active tab to green")
echo()
echo("Valid options are " .. validOptionsString)
echo("Remember to use 'emco save' to make your changes permanent, or 'emco load' to undo them and reset back to what you previously saved.")